#!/bin/bash

# Parâmetros:
# 1. Um arquivo assembly (asm) para ser compilado
# 2. Um diretório onde o arquivo compilado será armazenado

FILENAME=$1
DIR=${2:-./}

# Verifica se um arquivo foi passado como parâmetro
if [[ ! -n "$FILENAME" ]]; then
	echo "Erro: falta passar arquivo como parâmetro"
	exit 1
fi

# Verifica se o arquivo passado existe
if [[ ! -f "$FILENAME.asm" ]]; then
	echo "Erro: o arquivo '$FILENAME.asm' não existe."
	exit 1
fi

# Cria diretório se foi passado
if [[ "$DIR" != "./" ]]; then
	mkdir -p "$DIR"
fi

# Compila o arquivo
nasm -f elf64 $FILENAME.asm -o $FILENAME.o && \
ld $FILENAME.o -o "$DIR/$FILENAME" && \
rm -f "$FILENAME.o"
